name: OpenCode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  opencode:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: jhw7500/automation/.github/workflows/opencode.yml@78cdad332ca85d3a4c3fb51be0a203b988485c86
    secrets:
      ZHIPU_API_KEY: ${{ secrets.ZHIPU_API_KEY }}
